wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.5
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1721881782
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      - 105
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      - 105
      3:
      - 1
      - 7
      - 23
      - 66
      4: 3.9.19
      5: 0.17.5
      8:
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-Adam
      5: 1
      6:
      - 1
